# Generated by Django 3.2.5 on 2021-07-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, default='Write a short description', max_length=255, null=True),
        ),
    ]
